### PR TITLE
test: skip file-descriptor test if lsof is unavailable

### LINKED ISSUE #110: Tests are failing when `lsof` is not available
The CI is failing on the debian target because `lsof` is not available on the system.
The code triggering this is [here](https://github.com/mirage/index/blob/master/test/unix/force_merge.ml#L34-L37). The test case should probably be skipped instead of failing.

### PR DESCRIPTION
**Pull request by CraigFe**
Fixes #110.

### CODE REVIEW

File: test/unix/force_merge.ml [hunk 1]
```diff
@@ -25,49 +25,64 @@ let test_one_entry r k v =
       Alcotest.failf "Inserted value is not present anymore: %s." k
 
 let test_fd () =
+  let ( >>= ) x f = match x with `Ok x -> f x | err -> err in
```
Comment (pascutto) [inline test/unix/force_merge.ml]: Can you pick another infix operator, just to ease the potential migration to `lwt` (if that ever happens).

Comment (CraigFe) [reply test/unix/force_merge.ml]: This function doesn't actually use the Index API at all, but have switched to `>>?` regardless.
